version: '3.5'
services:
  php-app:
    image: php:apache
    container_name: app
    ports:
      - '80:80'
    restart: unless-stopped
    depends_on: 
      - app-db
      - app-redis
    networks:
      - internet
      - appnet

  app-db:
    image: postgres
    container_name: app-postgres
    restart: unless-stopped
    environment:
      - 'POSTGRES_PASSWORD=mypas'
    networks:
      - appnet

  app-redis:
    image: redis
    container_name: app-redis
    restart: unless-stopped
    networks:
      - appnet
networks:
  internet:
    name: internet
    driver: bridge
  appnet:
    name: appnet
    driver: bridge
